name: format
on: 
  push:
jobs:
  main:
    runs-on: [self-hosted, c8g.medium]
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun ci
      - run: bun run format
      - run: git diff --exit-code
